#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate the bounded deterministic Immersive Energistics review gallery."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

import cases


ROOT = Path(__file__).resolve().parent


def text_bytes(value: str) -> bytes:
    return (value.rstrip() + "\n").encode("utf-8")


def json_bytes(value: object) -> bytes:
    return text_bytes(json.dumps(value, indent=2, sort_keys=True))


def placements_tsv() -> bytes:
    lines = ["case_id\tlabel\tx\ty\tz\tblock_state\texpected"]
    lines.extend(
        "\t".join(
            (
                placement.case_id,
                placement.label,
                str(placement.x),
                str(placement.y),
                str(placement.z),
                placement.block_state,
                placement.expected,
            )
        )
        for placement in cases.PLACEMENTS
    )
    return text_bytes("\n".join(lines))


def wires_tsv() -> bytes:
    lines = [
        "span_id\tlabel\twire_item\tstart_case\tstart_xyz\tend_case\tend_xyz"
    ]
    for span in cases.WIRE_SPANS:
        start = cases.PLACEMENT_BY_ID[span.start_case]
        end = cases.PLACEMENT_BY_ID[span.end_case]
        lines.append(
            "\t".join(
                (
                    span.span_id,
                    span.label,
                    span.wire_item,
                    span.start_case,
                    f"{start.x} {start.y} {start.z}",
                    span.end_case,
                    f"{end.x} {end.y} {end.z}",
                )
            )
        )
    return text_bytes("\n".join(lines))


def clear_function() -> bytes:
    minimum_x, minimum_y, minimum_z, maximum_x, maximum_y, maximum_z = cases.ENVELOPE
    return text_bytes(
        "# Generated by gallery/generate.py; do not edit.\n"
        f"fill {minimum_x} {minimum_y} {minimum_z} "
        f"{maximum_x} {maximum_y} {maximum_z} minecraft:air"
    )


def sign_state(label: cases.Label) -> str:
    messages = ",".join(
        f"'{json.dumps({'text': line}, separators=(',', ':'))}'"
        for line in (label.line_1, label.line_2, "", "")
    )
    return (
        "minecraft:oak_sign[rotation=12,waterlogged=false]"
        f"{{front_text:{{messages:[{messages}]}}}}"
    )


def build_function() -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"function {cases.NAMESPACE}:clear",
    ]
    for support_x, support_y, support_z in sorted(
        {placement.support for placement in cases.PLACEMENTS}
    ):
        lines.append(
            f"setblock {support_x} {support_y} {support_z} minecraft:polished_andesite"
        )
    for label in cases.LABELS:
        lines.extend(
            (
                f"setblock {label.x} {label.y - 1} {label.z} minecraft:smooth_stone",
                f"setblock {label.x} {label.y} {label.z} {sign_state(label)}",
            )
        )
    for placement in cases.PLACEMENTS:
        lines.extend(
            (
                f"# {placement.case_id}: {placement.label}",
                f"setblock {placement.x} {placement.y} {placement.z} {placement.block_state}",
            )
        )
    lines.extend(
        (
            f"function {cases.NAMESPACE}:verify",
            "tellraw @a {\"text\":\"Gallery built; run /function "
            f"{cases.NAMESPACE}:wire_kit as a player\",\"color\":\"yellow\"}}",
        )
    )
    return text_bytes("\n".join(lines))


def verify_function() -> bytes:
    lines = ["# Generated by gallery/generate.py; do not edit."]
    for placement in cases.PLACEMENTS:
        lines.append(
            f"execute unless block {placement.x} {placement.y} {placement.z} "
            f"{placement.block_state} run tellraw @a "
            f"{{\"text\":\"gallery mismatch: {placement.case_id}\",\"color\":\"red\"}}"
        )
    lines.append(
        "tellraw @a {\"text\":\"Immersive Energistics block gallery checked\","
        "\"color\":\"yellow\"}"
    )
    return text_bytes("\n".join(lines))


def wire_kit_function() -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        "give @s immeng:wirecoil_me 2",
        "give @s immeng:wirecoil_me_dense 2",
        "tellraw @s {\"text\":\"Right-click each listed pair in order:\",\"color\":\"yellow\"}",
    ]
    for span in cases.WIRE_SPANS:
        start = cases.PLACEMENT_BY_ID[span.start_case]
        end = cases.PLACEMENT_BY_ID[span.end_case]
        lines.append(
            "tellraw @s "
            f"{{\"text\":\"{span.span_id}: [{start.x} {start.y} {start.z}] -> "
            f"[{end.x} {end.y} {end.z}] using {span.wire_item}\",\"color\":\"aqua\"}}"
        )
    lines.append(
        "tellraw @s {\"text\":\"Leave [204 101 202] unwired; then run /save-all flush\",\"color\":\"gold\"}"
    )
    return text_bytes("\n".join(lines))


def base_files() -> dict[Path, bytes]:
    function_root = Path(f"datapack/data/{cases.NAMESPACE}/function")
    tp_x, tp_y, tp_z, tp_yaw, tp_pitch = cases.TELEPORT
    return {
        Path("placements.tsv"): placements_tsv(),
        Path("wires.tsv"): wires_tsv(),
        Path("datapack/pack.mcmeta"): json_bytes(
            {
                "pack": {
                    "description": "ATM 1.2.0 Immersive Energistics gallery",
                    "pack_format": 48,
                }
            }
        ),
        Path("datapack/data/minecraft/tags/function/load.json"): json_bytes(
            {"values": [f"{cases.NAMESPACE}:load"]}
        ),
        function_root / "load.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            "tellraw @a {\"text\":\"Immersive Energistics gallery loaded; run "
            f"/function {cases.NAMESPACE}:build\",\"color\":\"yellow\"}}"
        ),
        function_root / "clear.mcfunction": clear_function(),
        function_root / "build.mcfunction": build_function(),
        function_root / "verify.mcfunction": verify_function(),
        function_root / "wire_kit.mcfunction": wire_kit_function(),
        function_root / "tp.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"tp @s {tp_x} {tp_y} {tp_z} {tp_yaw} {tp_pitch}"
        ),
        function_root / "release.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"function {cases.NAMESPACE}:clear"
        ),
    }


def generated_files() -> dict[Path, bytes]:
    files = base_files()
    checksum = "".join(
        f"{hashlib.sha256(payload).hexdigest()}  {path.as_posix()}\n"
        for path, payload in sorted(files.items(), key=lambda row: row[0].as_posix())
    )
    files[Path("SHA256SUMS")] = checksum.encode("ascii")
    return files


def stale_generated_functions(expected: set[Path]) -> tuple[Path, ...]:
    function_root = ROOT / f"datapack/data/{cases.NAMESPACE}/function"
    if not function_root.is_dir():
        return ()
    return tuple(
        path
        for path in sorted(function_root.glob("*.mcfunction"))
        if path.relative_to(ROOT) not in expected
    )


def write_or_check(check: bool) -> int:
    generated = generated_files()
    expected = set(generated)
    failures = []
    for relative, payload in generated.items():
        destination = ROOT / relative
        if check:
            if not destination.is_file() or destination.read_bytes() != payload:
                failures.append(relative.as_posix())
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(payload)
    stale = stale_generated_functions(expected)
    if check:
        failures.extend(path.relative_to(ROOT).as_posix() for path in stale)
    else:
        for path in stale:
            path.unlink()
    if failures:
        print(f"generated gallery differs: {', '.join(failures)}", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return write_or_check(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
