# Generated by gallery/generate.py; do not edit.
function immeng_gallery:clear
setblock 176 100 176 minecraft:polished_andesite
setblock 176 100 182 minecraft:polished_andesite
setblock 176 100 190 minecraft:polished_andesite
setblock 176 100 196 minecraft:polished_andesite
setblock 180 102 176 minecraft:polished_andesite
setblock 180 102 182 minecraft:polished_andesite
setblock 184 101 175 minecraft:polished_andesite
setblock 184 101 181 minecraft:polished_andesite
setblock 188 100 190 minecraft:polished_andesite
setblock 188 101 177 minecraft:polished_andesite
setblock 188 101 183 minecraft:polished_andesite
setblock 190 100 196 minecraft:polished_andesite
setblock 193 101 176 minecraft:polished_andesite
setblock 193 101 182 minecraft:polished_andesite
setblock 195 101 176 minecraft:polished_andesite
setblock 195 101 182 minecraft:polished_andesite
setblock 204 100 202 minecraft:polished_andesite
setblock 174 99 176 minecraft:smooth_stone
setblock 174 100 176 minecraft:oak_sign[rotation=12,waterlogged=false]{front_text:{messages:['{"text":"ME CONNECTOR"}','{"text":"SIX FACINGS"}','{"text":""}','{"text":""}']}}
setblock 174 99 182 minecraft:smooth_stone
setblock 174 100 182 minecraft:oak_sign[rotation=12,waterlogged=false]{front_text:{messages:['{"text":"ME RELAY"}','{"text":"SIX FACINGS"}','{"text":""}','{"text":""}']}}
setblock 174 99 190 minecraft:smooth_stone
setblock 174 100 190 minecraft:oak_sign[rotation=12,waterlogged=false]{front_text:{messages:['{"text":"ME DIRECT"}','{"text":"12 BLOCKS"}','{"text":""}','{"text":""}']}}
setblock 174 99 196 minecraft:smooth_stone
setblock 174 100 196 minecraft:oak_sign[rotation=12,waterlogged=false]{front_text:{messages:['{"text":"DENSE WIRE"}','{"text":"TO RELAY"}','{"text":""}','{"text":""}']}}
setblock 202 99 202 minecraft:smooth_stone
setblock 202 100 202 minecraft:oak_sign[rotation=12,waterlogged=false]{front_text:{messages:['{"text":"NO WIRE"}','{"text":"FALLBACK"}','{"text":""}','{"text":""}']}}
# connector-me-down: connector me facing down
setblock 176 101 176 immeng:connector_me[facing=down,waterlogged=false]
# connector-me-up: connector me facing up
setblock 180 101 176 immeng:connector_me[facing=up,waterlogged=false]
# connector-me-north: connector me facing north
setblock 184 101 176 immeng:connector_me[facing=north,waterlogged=false]
# connector-me-south: connector me facing south
setblock 188 101 176 immeng:connector_me[facing=south,waterlogged=false]
# connector-me-east: connector me facing east
setblock 192 101 176 immeng:connector_me[facing=east,waterlogged=false]
# connector-me-west: connector me facing west
setblock 196 101 176 immeng:connector_me[facing=west,waterlogged=false]
# connector-me-relay-down: connector me relay facing down
setblock 176 101 182 immeng:connector_me_relay[facing=down,waterlogged=false]
# connector-me-relay-up: connector me relay facing up
setblock 180 101 182 immeng:connector_me_relay[facing=up,waterlogged=false]
# connector-me-relay-north: connector me relay facing north
setblock 184 101 182 immeng:connector_me_relay[facing=north,waterlogged=false]
# connector-me-relay-south: connector me relay facing south
setblock 188 101 182 immeng:connector_me_relay[facing=south,waterlogged=false]
# connector-me-relay-east: connector me relay facing east
setblock 192 101 182 immeng:connector_me_relay[facing=east,waterlogged=false]
# connector-me-relay-west: connector me relay facing west
setblock 196 101 182 immeng:connector_me_relay[facing=west,waterlogged=false]
# me-direct-a: ME direct endpoint A
setblock 176 101 190 immeng:connector_me[facing=down,waterlogged=false]
# me-direct-b: ME direct endpoint B
setblock 188 101 190 immeng:connector_me[facing=down,waterlogged=false]
# dense-relay-end: dense ME relay endpoint
setblock 176 101 196 immeng:connector_me[facing=down,waterlogged=false]
# dense-relay-hub: dense ME relay hub
setblock 190 101 196 immeng:connector_me_relay[facing=down,waterlogged=false]
# absent-wire-relay-control: isolated relay: absent-wire safe fallback
setblock 204 101 202 immeng:connector_me_relay[facing=down,waterlogged=false]
function immeng_gallery:verify
tellraw @a {"text":"Gallery built; run /function immeng_gallery:wire_kit as a player","color":"yellow"}
