# Generated by gallery/generate.py; do not edit.
execute unless block 176 101 176 immeng:connector_me[facing=down,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-me-down","color":"red"}
execute unless block 180 101 176 immeng:connector_me[facing=up,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-me-up","color":"red"}
execute unless block 184 101 176 immeng:connector_me[facing=north,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-me-north","color":"red"}
execute unless block 188 101 176 immeng:connector_me[facing=south,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-me-south","color":"red"}
execute unless block 192 101 176 immeng:connector_me[facing=east,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-me-east","color":"red"}
execute unless block 196 101 176 immeng:connector_me[facing=west,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-me-west","color":"red"}
execute unless block 176 101 182 immeng:connector_me_relay[facing=down,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-me-relay-down","color":"red"}
execute unless block 180 101 182 immeng:connector_me_relay[facing=up,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-me-relay-up","color":"red"}
execute unless block 184 101 182 immeng:connector_me_relay[facing=north,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-me-relay-north","color":"red"}
execute unless block 188 101 182 immeng:connector_me_relay[facing=south,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-me-relay-south","color":"red"}
execute unless block 192 101 182 immeng:connector_me_relay[facing=east,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-me-relay-east","color":"red"}
execute unless block 196 101 182 immeng:connector_me_relay[facing=west,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-me-relay-west","color":"red"}
execute unless block 176 101 190 immeng:connector_me[facing=down,waterlogged=false] run tellraw @a {"text":"gallery mismatch: me-direct-a","color":"red"}
execute unless block 188 101 190 immeng:connector_me[facing=down,waterlogged=false] run tellraw @a {"text":"gallery mismatch: me-direct-b","color":"red"}
execute unless block 176 101 196 immeng:connector_me[facing=down,waterlogged=false] run tellraw @a {"text":"gallery mismatch: dense-relay-end","color":"red"}
execute unless block 190 101 196 immeng:connector_me_relay[facing=down,waterlogged=false] run tellraw @a {"text":"gallery mismatch: dense-relay-hub","color":"red"}
execute unless block 204 101 202 immeng:connector_me_relay[facing=down,waterlogged=false] run tellraw @a {"text":"gallery mismatch: absent-wire-relay-control","color":"red"}
tellraw @a {"text":"Immersive Energistics block gallery checked","color":"yellow"}
