# Generated by gallery/generate.py; do not edit.
give @s immeng:wirecoil_me 2
give @s immeng:wirecoil_me_dense 2
tellraw @s {"text":"Right-click each listed pair in order:","color":"yellow"}
tellraw @s {"text":"me-direct: [176 101 190] -> [188 101 190] using immeng:wirecoil_me","color":"aqua"}
tellraw @s {"text":"dense-relay: [176 101 196] -> [190 101 196] using immeng:wirecoil_me_dense","color":"aqua"}
tellraw @s {"text":"Leave [204 101 202] unwired; then run /save-all flush","color":"gold"}
